package cz.cvut.fel.mygs.variables


enum class ResponseConstants(val value: String) {
    SUCCESS("success"),
    ERROR("error"),
    UNKNOWN("UNKN"),


    //USER
    INVALID_CREDENTIAL("USR001"),
    INVALID_EMAIL("USR002"),
    EMAIL_ALREADY_EXIST("USR003"),
    INVALID_PHONE("USR004"),
    INVALID_USER_DATA("USR005"),
    SHORT_PASSWORD("USR006"),
    USER_IS_NOT_EXIST("USR007"),
    AUTHORIZATION_FAILED("USR008"),
    USER_ALREADY_VERIFIED("USR009"),
    INVALID_CODE("USR010"),
    CODE_NOT_CONFIRMED("USR011"),
    PASSWORD_MISMATCH("USR012"),
    INVALID_PASSWORD("USR013"),

    //CAR
    EMPTY_BRAND("CAR001"),
    EMPTY_NUMBER("CAR002"),
    UNKNOWN_GASOLINE_TYPE("CAR003"),
    CAR_NOT_FOUND("CAR004"),

    //CARD
    CARD_NUMBER_EMPTY("CRD001"),
    WRONG_CARD_NUMBER_FORMAT("CRD002"),
    EMPTY_EXPIRATION_DATE("CRD003"),
    CARD_EXPIRED("CRD004"),
    WRONG_CVV_FORMAT("CRD005"),
    CARD_NOT_FOUND("CRD006"),
    FAIL_TO_SAVE_CARD("CRD007"),

    //ORDER
    WRONG_AMOUNT("ORD001"),
    ORDER_NOT_FOUND("ORD002"),

    //GAS STATION
    GAS_STATION_NOT_FOUND("GST001"),
    EMPTY_NAME("GST002"),
    EMPTY_SERVICES("GST003"),
    EMPTY_PAYMENT_METHODS("GST004"),
    WRONG_MANAGER("GST005"),
    REFUELING_STAND_ALREADY_EXIST("GST006"),

    //OFFER
    OFFER_NOT_FOUND("OFR001"),

    //FUEL
    FUEL_NOT_FOUND("FUE001"),

    //FEEDBACK
    EMPTY_CONTENT("FEB001"),
    EMPTY_TITLE("FEB002"),
    WRONG_TITLE_LENGTH("FEB002")
}
